src/Entity/Ad.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *     fields = {"title"},
 *     message = "Une autre annonce possède déjà ce titre"
 * )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="Votre introduction doit faire plus de 20 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre description doit faire plus de 100 caractères")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad", cascade={"remove"})
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * @param User $author
     * @return mixed|null
     * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach($this->comments as $comment)
        {
            if ($comment->getAuthor() === $author) return $comment;
        }
        return null;
    }

    /**
     * @return float|int
     * Permet d'obtenir moyenne globale des notes pour cette annonce
     */
    public function getAvgRatings()
    {
        //Calculer la somme des notations
        $sum = array_reduce($this->comments->toArray(), function($total, $comment) {
            return $total + $comment->getRating();
        }, 0);
        //Faire la division
        if(count($this->comments) > 0) return $sum / count($this->comments);
        return 0;
    }

    public function getNotAvailableDays()
    {
        $notAvailableDays = [];
        foreach ($this->bookings as $booking)
        {
            //Calculer jours entre date arrivée et départ
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );
            $days = array_map(function($dayTimestamp) {
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);
            $notAvailableDays = array_merge($notAvailableDays, $days);

        }

        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"email"},
 *      message="Cette adresse mail est déjà utilisée"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champ obligatoire")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champ obligatoire")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez indiquer une URL valide pour votre avatar")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="Les mots de passe ne correspondent pas")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, minMessage="Votre description foit faire au moins 10 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre description foit faire au moins 100 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author", cascade={"remove"})
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker", cascade={"remove"})
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true, cascade={"remove"})
     */
    private $comments;

    public function getFullName()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    /**
     * Permet d'initialiser le slug
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles() //Retourne liste de rôles en chaînes de caracrtères
    {
        //$roles = $this->userRoles->toArray(); toArray = transforme ArrayCollection en tableau classique PHP

        $roles = $this->userRoles->map(function($role){
            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function getPassword()
    {
        // TODO: Implement getPassword() method.
        return $this->hash;
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function getUsername()
    {
        // TODO: Implement getUsername() method.
        return $this->email;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug': ad.slug}) %}
<div class="col-md-4">
    <div class="card bg-light mb-3">
        <div class="card-header text-center">
            {{ ad.rooms }} chambres, <strong>{{ ad.price }}€/nuit</strong><br>
            {% if ad.comments | length > 0 %}
                {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %}
            {% else %}
                <small>Pas encore noté</small>
            {% endif %}
        </div>
        <a href="{{ url }}">
            <img src="{{ ad.coverImage }}" alt="Image de l'appartement" style="height: 200px; width: 100%; display: block">
        </a>
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ url }}">
                    {{ ad.title }}
                </a>
            </h4>
            <p class="card-text">
                {{ ad.introduction }}
            </p>
            <a href="{{ url }}" class="btn btn-secondary">En savoir plus</a>
            {% if app.user and app.user == ad.author %}
                <a href="{{ path('ad_edit', {'slug': ad.slug}) }}" class="btn btn-secondary">Modifier</a>
            {% endif %}
        </div>
    </div>
</div>

templates/ad/_collection.html.twig
{% block _ad_images_widget %}
    <p>Ici, vous pouvez ajouter vos images</p>
    {{ form_widget(form) }}

    {# Pour gérer bug #}
    <input type="hidden" id="widget-counter" value="0">

    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">Ajouter image</button>
    </div>
{% endblock %}

{% block _ad_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _ad_images_entry_widget %}
    <div class="form-group" id="block_{{ id }}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url) }}
                        {{ form_errors(form.url) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                        {{ form_errors(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger">Supprimer</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}

    <div class="container">
        <h1>Editer une annonce : {{ ad.title }}</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">{{ button_label|default('Editer l\'annonce') }}</button>
        {{ form_end(form) }}
    </div>

{% endblock %}

{% block _ad_images_widget %}
    <p>Ici, vous pouvez éditer vos images</p>
    {{ form_widget(form) }}

    {# Pour gérer bug #}
    <input type="hidden" id="widget-counter" value="0">

    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">Ajouter image</button>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="/js/ad.js"></script>
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos annonces{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="my-3">Les annonces de nos hôtes</h1>
        <div class="row">
            {% for ad in ads %}
                {% include 'ad/_ad.html.twig' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/ad/new.html.twig
{% extends'base.html.twig' %}

{% block title %}Création d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}

    <div class="container">
        <h1>Créer une annonce</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">{{ button_label|default('Créer l\'annonce') }}</button>
        {{ form_end(form) }}
    </div>

{% endblock %}

{% block javascripts %}
    <script src="/js/ad.js"></script>
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ ad.title }}
{% endblock %}

{% block body %}

    <div class="ad-title" style="background-image: url({{ ad.coverImage }})">
        <div class="container">
            <h1>{{ ad.title }}</h1>
            <p>{{ ad.introduction }}</p>
            <p class="h2">
                <strong>{{ ad.rooms }} chambres</strong> pour <strong>{{ ad.price }}€</strong>/nuits
            </p>
            <a href="{{ path('booking_create', {'slug': ad.slug}) }}" class="btn btn-primary">Réserver !</a>
            {% if app.user and app.user == ad.author %}
                <a href="{{ path('ad_edit', {'slug': ad.slug}) }}" class="btn btn-secondary">Modifier l'annonce</a>
                <a href="{{ path('ad_delete', {'slug': ad.slug}) }}" class="btn btn-danger"
                   onclick="return confirm(`Êtes-vous sûr de vouloir supprimer l'annonce {{ ad.title }} ?`)">Supprimer l'annonce</a>
            {% endif %}
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3">
                {{ ad.content | raw }}
{#Carousel#}
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in ad.images %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" class="{% if loop.first %}active{% endif %}"></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in ad.images %} {#ad.images car entités liées par une relation#}
                            <div class="carousel-item {% if loop.first %}active{% endif %}">
                                <img class="d-block w-100" src="{{ image.url }}" alt="Ad Slide">
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>{{ ad.title }}</h5>
                                    <p>{{ image.caption }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <hr>
                {% if ad.comments | length > 0 %}
                    <h2 class="mb-3">Commentaires de nos voyageurs: </h2>
                    <div class="alert alert-info">
                        <h4 class="alert-heading text-center">
                            <div class="row align-items-center">
                                <div class="col">
                                    Note globale donnée par nos voyageurs
                                </div>
                                <div class="col">
                                    {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %} <br>
                                    <small>(calculé sur {{ ad.comments | length }} avis)</small>
                                </div>
                            </div>
                        </h4>
                    </div>
                    {% for comment in ad.comments %}
                        <div class="bg-light rounded mb-3 py-3 px-3">
                            <strong>{{ comment.author.firstName }}</strong> a dit :
                            <blockquote>
                                {{ comment.content }}
                            </blockquote>
                            <strong>Note donnée : </strong>
                            {% include 'partials/rating.html.twig' with {'rating': comment.rating } %}
                        </div>
                    {% endfor %}
                {% else %}
                    <h2>Cette annonce n'a pas encore reçu de commentaires.</h2>
                {% endif %}
{#Fin Carousel#}
            </div>
            <div class="col">
                {% set a = ad.author %}
                <div class="row">
                    <div class="col-3">
                        <a href="{{ path('user_show', {'slug': a.slug}) }}"><img class="avatar" src="{{ a.picture }}" alt="avatar de {{ a.fullName }}"></a>
                    </div>
                    <div class="col">
                        <a href="{{ path('user_show', {'slug': a.slug}) }}">
                            <h3>{{ a.fullname }}</h3>
                        </a>
                        <span class="badge badge-primary">{{ a.ads|length }} annonces</span>
                    </div>
                </div>
                {{ a.description|raw }}
            </div>
        </div>
    </div>

{% endblock %}